/**
 * Single canonical, alphabetized language list -- shared by every dialog that
 * lets someone pick a language (Client Demand, Add a Lead, Contractor Add a
 * Lead). Previously this exact 56-language set was hardcoded, region-grouped
 * (not alphabetized), and duplicated byte-for-byte across three files -- any
 * update had to be made in three places, and none of them were sorted for
 * browsability.
 */
export const STANDARD_LANGUAGES = [
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Cantonese",
  "Castilian Spanish",
  "Catalan",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "English (AUS)",
  "English (Canada)",
  "English (UK)",
  "Finnish",
  "French",
  "French (Canadian)",
  "French (Parisian)",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Korean",
  "Malay",
  "Malayalam",
  "Marathi",
  "Norwegian",
  "Odia",
  "Polish",
  "Portuguese (Brazilian)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Romanian",
  "Russian",
  "Slovak",
  "Slovenian",
  "Spanish (LatAm)",
  "Spanish (Latin America)",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
];
