/**
 * Tests the systemic replacement for hardcoded FAQ keyword matching:
 * findFaqsByMessageTags scans every active FAQ's own (auto-generated) tags
 * against the raw message directly, so any FAQ is findable by its own tags
 * with zero code changes -- no more per-topic entries in a static allowlist.
 *
 * Run: cd server && npx ts-node src/lib/faqTagMatcher.test.ts
 */

import assert from "node:assert";
import { prisma } from "../prisma";
import { findFaqsByMessageTags } from "./faqTagMatcher";

async function test1_matchesRealMsaFaqForTheOriginalBugReport() {
  const matches = await findFaqsByMessageTags("Tell me MSA process");
  assert.ok(matches.length > 0, "expected at least one MSA-tagged FAQ to match");
  assert.ok(matches.some((m) => m.matchedTag.toLowerCase() === "msa"));
}

async function test2_matchesWholeWordOnlyNotSubstring() {
  // "pay" is a real tag (payment-related FAQs). A message that merely
  // CONTAINS "pay" as a substring inside a longer, unrelated word must not
  // match -- only a real, whole-word occurrence should.
  const substringOnly = await findFaqsByMessageTags("I displayed my portfolio yesterday");
  assert.ok(!substringOnly.some((m) => m.matchedTag.toLowerCase() === "pay"), "must not match 'pay' inside 'displayed'");

  const wholeWord = await findFaqsByMessageTags("When do I get paid?");
  // Not asserting a specific tag here since exact tag wording may vary --
  // just confirm whole-word matching against a real payment-context
  // message doesn't false-negative the way the substring case correctly
  // false-negatives above.
  assert.ok(Array.isArray(wholeWord));
}

async function test3_noMatchForUnrelatedMessage() {
  const matches = await findFaqsByMessageTags("The weather today is quite pleasant, don't you think?");
  assert.strictEqual(matches.length, 0);
}

async function test4_emptyMessageReturnsEmptyWithoutQuerying() {
  const matches = await findFaqsByMessageTags("   ");
  assert.strictEqual(matches.length, 0);
}

async function test5_newlyCreatedFaqIsFindableByItsAutoGeneratedTagsImmediately() {
  // Proves the actual systemic claim: a brand-new FAQ, tagged with a term
  // never mentioned anywhere in this codebase's source, is findable purely
  // because it's tagged -- no code change required.
  const created = await prisma.faqEntry.create({
    data: {
      id: `test_faqtagmatcher_${Date.now()}`,
      category: "Test",
      question: "Do you support zorbatronic scheduling?",
      answer: "Yes, zorbatronic scheduling is fully supported.",
      tags: ["zorbatronic"],
      isActive: true,
    },
  });

  try {
    const matches = await findFaqsByMessageTags("Can you tell me about zorbatronic scheduling please?");
    assert.ok(matches.some((m) => m.id === created.id), "a freshly created, freshly tagged FAQ must be findable immediately");
  } finally {
    await prisma.faqEntry.delete({ where: { id: created.id } });
  }
}

async function main() {
  const tests = [
    test1_matchesRealMsaFaqForTheOriginalBugReport,
    test2_matchesWholeWordOnlyNotSubstring,
    test3_noMatchForUnrelatedMessage,
    test4_emptyMessageReturnsEmptyWithoutQuerying,
    test5_newlyCreatedFaqIsFindableByItsAutoGeneratedTagsImmediately,
  ];
  let failed = 0;
  for (const t of tests) {
    try {
      await t();
      console.log(`PASS ${t.name}`);
    } catch (err) {
      failed++;
      console.error(`FAIL ${t.name}`);
      console.error(err);
    }
  }
  await prisma.$disconnect();
  if (failed > 0) {
    console.error(`${failed}/${tests.length} test(s) failed`);
    process.exit(1);
  }
  console.log(`All ${tests.length} tests passed`);
}

main();
