-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'ENRICHMENT_COMPLETE';
ALTER TYPE "NotificationType" ADD VALUE 'DAILY_DEMAND_SUMMARY';
ALTER TYPE "NotificationType" ADD VALUE 'WEEKLY_LEADS_SUMMARY';
ALTER TYPE "NotificationType" ADD VALUE 'WEEKLY_PERFORMANCE_SUMMARY';
