/**
 * Maps a free-text country name (as stored on Lead.country) to its ISO
 * 3166-1 alpha-2 code, for the `address_country` param G3's apply form
 * expects. Covers common country names and their frequent variants
 * (e.g. "USA"/"United States"/"US") rather than every name a general
 * i18n package would recognize -- extend this table as new spellings
 * show up in real data instead of reaching for a dependency for a
 * fixed-size lookup.
 *
 * An unrecognized country returns undefined -- callers must omit the
 * `address_country` param entirely in that case. Never send a guess or
 * a placeholder for a country we can't confidently map.
 */
const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  "afghanistan": "AF",
  "albania": "AL",
  "algeria": "DZ",
  "argentina": "AR",
  "armenia": "AM",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahrain": "BH",
  "bangladesh": "BD",
  "belarus": "BY",
  "belgium": "BE",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "brazil": "BR",
  "bulgaria": "BG",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "costa rica": "CR",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech republic": "CZ",
  "czechia": "CZ",
  "denmark": "DK",
  "dominican republic": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "estonia": "EE",
  "ethiopia": "ET",
  "finland": "FI",
  "france": "FR",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "great britain": "GB",
  "greece": "GR",
  "guatemala": "GT",
  "honduras": "HN",
  "hong kong": "HK",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "ivory coast": "CI",
  "jamaica": "JM",
  "japan": "JP",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kuwait": "KW",
  "latvia": "LV",
  "lebanon": "LB",
  "lithuania": "LT",
  "luxembourg": "LU",
  "malaysia": "MY",
  "malta": "MT",
  "mexico": "MX",
  "moldova": "MD",
  "morocco": "MA",
  "myanmar": "MM",
  "nepal": "NP",
  "netherlands": "NL",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "nigeria": "NG",
  "north macedonia": "MK",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "panama": "PA",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "poland": "PL",
  "portugal": "PT",
  "qatar": "QA",
  "republic of ireland": "IE",
  "romania": "RO",
  "russia": "RU",
  "russian federation": "RU",
  "saudi arabia": "SA",
  "serbia": "RS",
  "singapore": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "south africa": "ZA",
  "south korea": "KR",
  "spain": "ES",
  "sri lanka": "LK",
  "sweden": "SE",
  "switzerland": "CH",
  "taiwan": "TW",
  "thailand": "TH",
  "tunisia": "TN",
  "turkey": "TR",
  "türkiye": "TR",
  "uae": "AE",
  "uk": "GB",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united states": "US",
  "united states of america": "US",
  "uruguay": "UY",
  "usa": "US",
  "u.s.": "US",
  "u.s.a.": "US",
  "u.k.": "GB",
  "uzbekistan": "UZ",
  "venezuela": "VE",
  "vietnam": "VN",
  "viet nam": "VN",
  "yemen": "YE",
  "zimbabwe": "ZW",
};

export function countryToIso2(country: string | null | undefined): string | undefined {
  if (!country) return undefined;
  const key = country.trim().toLowerCase();
  if (!key) return undefined;
  return COUNTRY_NAME_TO_ISO2[key];
}

// Exported for tests / debugging -- callers should use countryToIso2().
export { COUNTRY_NAME_TO_ISO2 };
